

# Subset "war_daily_bat" to only include data from after 1985
warBat <- war_daily_bat[which(war_daily_bat$year_ID >= "1980"), ]

# Subset "war_daily_bat" to only include data from after 1985
warPitch <- war_daily_pitch[which(war_daily_pitch$year_ID >= "1980"), ]

warBatNA <- na.omit(warBat)
warPitchNA <- na.omit(warPitch)

warBatNA$age <- as.numeric(warBatNA$age)
warBatNA$year_ID <- as.numeric(warBatNA$year_ID)
warBatNA$PA <- as.numeric(warBatNA$PA)
warBatNA$G <- as.numeric(warBatNA$G)
warBatNA$Inn <- as.numeric(warBatNA$Inn)
warBatNA$runs_bat <- as.numeric(warBatNA$runs_bat)
warBatNA$runs_br <- as.numeric(warBatNA$runs_br)
warBatNA$runs_dp <- as.numeric(warBatNA$runs_dp)
warBatNA$runs_field <- as.numeric(warBatNA$runs_field)
warBatNA$runs_infield <- as.numeric(warBatNA$runs_infield)
warBatNA$runs_outfield <- as.numeric(warBatNA$runs_outfield)
warBatNA$runs_catcher <- as.numeric(warBatNA$runs_catcher)
warBatNA$runs_good_plays <- as.numeric(warBatNA$runs_good_plays)
warBatNA$runs_defense <- as.numeric(warBatNA$runs_defense)
warBatNA$runs_position <- as.numeric(warBatNA$runs_position)
warBatNA$runs_position_p <- as.numeric(warBatNA$runs_position_p)
warBatNA$runs_replacement <- as.numeric(warBatNA$runs_replacement)
warBatNA$runs_above_rep <- as.numeric(warBatNA$runs_above_rep)
warBatNA$runs_above_avg <- as.numeric(warBatNA$runs_above_avg)
warBatNA$runs_above_avg_off <- as.numeric(warBatNA$runs_above_avg_off)
warBatNA$runs_above_avg_def <- as.numeric(warBatNA$runs_above_avg_def)
warBatNA$WAA <- as.numeric(warBatNA$WAA)
warBatNA$WAA_off <- as.numeric(warBatNA$WAA_off)
warBatNA$WAA_def <- as.numeric(warBatNA$WAA_def)
warBatNA$WAR <- as.numeric(warBatNA$WAR)
warBatNA$WAR_def <- as.numeric(warBatNA$WAR_def)
warBatNA$WAR_off <- as.numeric(warBatNA$WAR_off)
warBatNA$WAR_rep <- as.numeric(warBatNA$WAR_rep)
warBatNA$salary <- as.numeric(warBatNA$salary)
warBatNA$teamRpG <- as.numeric(warBatNA$teamRpG)
warBatNA$oppRpG <- as.numeric(warBatNA$oppRpG)
warBatNA$oppRpPA_rep <- as.numeric(warBatNA$oppRpPA_rep)
warBatNA$oppRpG_rep <- as.numeric(warBatNA$oppRpG_rep)
warBatNA$pyth_exponent <- as.numeric(warBatNA$pyth_exponent)
warBatNA$pyth_exponent_rep <- as.numeric(warBatNA$pyth_exponent_rep)
warBatNA$waa_win_perc <- as.numeric(warBatNA$waa_win_perc)
warBatNA$waa_win_perc_off <- as.numeric(warBatNA$waa_win_perc_off)
warBatNA$waa_win_perc_def <- as.numeric(warBatNA$waa_win_perc_def)
warBatNA$waa_win_perc_rep <- as.numeric(warBatNA$waa_win_perc_rep)
warBatNA$OPS_plus <- as.numeric(warBatNA$OPS_plus)
warBatNA$TOB_lg <- as.numeric(warBatNA$TOB_lg)
warBatNA$TB_lg <- as.numeric(warBatNA$TB_lg)
warBatNA$player_ID <- as.factor(warBatNA$player_ID)

warPitchNA$age <- as.numeric(warPitchNA$age)
warPitchNA$year_ID <- as.numeric(warPitchNA$year_ID)
warPitchNA$G <- as.numeric(warPitchNA$G)
warPitchNA$GS <- as.numeric(warPitchNA$GS)
warPitchNA$IPouts <- as.numeric(warPitchNA$IPouts)
warPitchNA$IPouts_start <- as.numeric(warPitchNA$IPouts_start)
warPitchNA$IPouts_relief <- as.numeric(warPitchNA$IPouts_relief)
warPitchNA$RA <- as.numeric(warPitchNA$RA)
warPitchNA$xRA <- as.numeric(warPitchNA$xRA)
warPitchNA$xRA_sprp_adj <- as.numeric(warPitchNA$xRA_sprp_adj)
warPitchNA$xRA_def_pitcher <- as.numeric(warPitchNA$xRA_def_pitcher)
warPitchNA$PPF <- as.numeric(warPitchNA$PPF)
warPitchNA$PPF_custom <- as.numeric(warPitchNA$PPF_custom)
warPitchNA$xRA_final <- as.numeric(warPitchNA$xRA_final)
warPitchNA$BIP <- as.numeric(warPitchNA$BIP)
warPitchNA$BIP_perc <- as.numeric(warPitchNA$BIP_perc)
warPitchNA$RS_def_total <- as.numeric(warPitchNA$RS_def_total)
warPitchNA$runs_above_avg <- as.numeric(warPitchNA$runs_above_avg)
warPitchNA$runs_above_avg_adj <- as.numeric(warPitchNA$runs_above_avg_adj)
warPitchNA$runs_above_rep <- as.numeric(warPitchNA$runs_above_rep)
warPitchNA$RpO_replacement <- as.numeric(warPitchNA$RpO_replacement)
warPitchNA$GR_leverage_index_avg <- as.numeric(warPitchNA$GR_leverage_index_avg)
warPitchNA$WAR <- as.numeric(warPitchNA$WAR)
warPitchNA$salary <- as.numeric(warPitchNA$salary)
warPitchNA$teamRpG <- as.numeric(warPitchNA$teamRpG)
warPitchNA$oppRpG <- as.numeric(warPitchNA$oppRpG)
warPitchNA$pyth_exponent <- as.numeric(warPitchNA$pyth_exponent)
warPitchNA$waa_win_perc <- as.numeric(warPitchNA$waa_win_perc)
warPitchNA$WAA <- as.numeric(warPitchNA$WAA)
warPitchNA$WAA_adj <- as.numeric(warPitchNA$WAA_adj)
warPitchNA$oppRpG_rep <- as.numeric(warPitchNA$oppRpG_rep)
warPitchNA$pyth_exponent_rep <- as.numeric(warPitchNA$pyth_exponent_rep)
warPitchNA$waa_win_perc_rep <- as.numeric(warPitchNA$waa_win_perc_rep)
warPitchNA$WAR_rep <- as.numeric(warPitchNA$WAR_rep)
warPitchNA$ERA_plus <- as.numeric(warPitchNA$ERA_plus)
warPitchNA$ER_lg <- as.numeric(warPitchNA$ER_lg)

View(warPitchNA)
View(warBatNA)

#EXPORT
write.csv(warPitchNA, "/users/anthonyzippay/desktop/warPitchNA.csv")
write.csv(warBatNA, "/users/anthonyzippay/desktop/warBatNA.csv")
